In [3]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
from sklearn.metrics import roc_auc_score, roc_curve

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

import warnings
warnings.filterwarnings("ignore")

In [4]:
#Data Gathering
df = pd.read_csv("Fish.csv")
df

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [5]:
# EDA
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


In [6]:
df.describe()

Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   26.247170   28.415723   31.227044    8.970994    4.417486
std     357.978317    9.996441   10.716328   11.610246    4.286208    1.685804
min       0.000000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000

In [7]:
df.isna().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [8]:
x = df.drop("Species",axis = 1)
y = df["Species"]

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25, random_state = 18, stratify = y)
x_train

Weight  Length1  Length2  Length3   Height   Width
74     40.0     13.8     15.0     16.0   3.8240  2.4320
132   430.0     35.5     38.0     40.5   7.2900  4.5765
43    150.0     20.4     22.0     24.7   5.8045  3.7544
78     78.0     16.8     18.7     19.4   5.1992  3.1234
91    130.0     20.5     22.5     24.0   5.8560  3.6240
..      ...      ...      ...      ...      ...     ...
109   514.0     30.5     32.8     34.0  10.0300  6.0180
36     69.0     16.5     18.2     20.3   5.2983  2.8217
82    110.0     19.0     21.0     22.5   5.6925  3.5550
121  1015.0     37.0     40.0     42.4  12.3808  7.4624
125  1100.0     40.1     43.0     45.5  12.5125  7.4165

[119 rows x 6 columns]

In [10]:
y_test.info()

<class 'pandas.core.series.Series'>
Int64Index: 40 entries, 135 to 123
Series name: Species
Non-Null Count  Dtype 
--------------  ----- 
40 non-null     object
dtypes: object(1)
memory usage: 640.0+ bytes


In [11]:
y_train.value_counts()

Perch        42
Bream        26
Roach        15
Pike         13
Smelt        10
Parkki        8
Whitefish     5
Name: Species, dtype: int64

In [12]:
y_test.value_counts()

Perch        14
Bream         9
Roach         5
Pike          4
Smelt         4
Parkki        3
Whitefish     1
Name: Species, dtype: int64

In [13]:
# Model Training
model = LogisticRegression(multi_class = "ovr")
model.fit(x_train,y_train)

LogisticRegression(multi_class='ovr')

In [14]:
# Evaluation 
def metrics(a,b):
    cnf_matrix = confusion_matrix(a,b)
    print("The Confusion Matrix is :\n", cnf_matrix)
    print("*"*40)
    accuracy = accuracy_score(a,b)
    print("Accuracy is :",accuracy)
    print("*"*40)

    clf_report = classification_report(a,b)
    print("Classification Report :\n",clf_report)
    print("*"*40)


    
    

In [15]:
# Evaluation for Testing Data 
y_pred = model.predict(x_test)
metrics(y_test,y_pred)

The Confusion Matrix is :
 [[ 9  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  0]
 [ 0  0 14  0  0  0  0]
 [ 0  0  0  4  0  0  0]
 [ 0  0  0  0  4  1  0]
 [ 0  0  0  0  0  4  0]
 [ 0  0  0  0  1  0  0]]
****************************************
Accuracy is : 0.95
****************************************
Classification Report :
               precision    recall  f1-score   support

       Bream       1.00      1.00      1.00         9
      Parkki       1.00      1.00      1.00         3
       Perch       1.00      1.00      1.00        14
        Pike       1.00      1.00      1.00         4
       Roach       0.80      0.80      0.80         5
       Smelt       0.80      1.00      0.89         4
   Whitefish       0.00      0.00      0.00         1

    accuracy                           0.95        40
   macro avg       0.80      0.83      0.81        40
weighted avg       0.93      0.95      0.94        40

****************************************


In [16]:
# Evaluation on training data
y_pred_train = model.predict(x_train)
metrics(y_train,y_pred_train)

The Confusion Matrix is :
 [[26  0  0  0  0  0  0]
 [ 0  8  0  0  0  0  0]
 [ 0  0 42  0  0  0  0]
 [ 0  0  0 13  0  0  0]
 [ 0  0  1  0 14  0  0]
 [ 0  0  0  0  0 10  0]
 [ 0  0  5  0  0  0  0]]
****************************************
Accuracy is : 0.9495798319327731
****************************************
Classification Report :
               precision    recall  f1-score   support

       Bream       1.00      1.00      1.00        26
      Parkki       1.00      1.00      1.00         8
       Perch       0.88      1.00      0.93        42
        Pike       1.00      1.00      1.00        13
       Roach       1.00      0.93      0.97        15
       Smelt       1.00      1.00      1.00        10
   Whitefish       0.00      0.00      0.00         5

    accuracy                           0.95       119
   macro avg       0.84      0.85      0.84       119
weighted avg       0.91      0.95      0.93       119

****************************************


In [17]:
x_train.head(1).T

74
Weight   40.000
Length1  13.800
Length2  15.000
Length3  16.000
Height    3.824
Width     2.432

In [23]:
Weight=45
Length1=19
Length2=16.000
Length3=17.000
Height=7
Width=5

test_array = np.array([Weight,Length1,Length2,Length3,Height,Width], ndmin = 2)
pred_class = model.predict(test_array)[0]
pred_class
# Glucose = 145.000
# BloodPressure =55.000
# SkinThickness = 38.000
# Insulin = 0.000
# BMI = 31.600
# DiabetesPedigreeFunction = 0.753
# Age = 55.000

# test_array = np.array([Glucose, BloodPressure,SkinThickness, Insulin, BMI,
#                       DiabetesPedigreeFunction, Age ], ndmin = 2)
# test_array

# pred_Class = logistic_clf.predict(test_array)[0]
# print("Predicted CLass :",pred_Class) # Threshold = 0.5

'Perch'

In [24]:
import pickle

with open("Logistic_fishspecies_detection.pkl","wb") as f:
    pickle.dump(model,f)